#!/usr/bin/python

# Copyright (C) 2013, Abel Sinkovics (abel@sinkovics.hu)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import xml.sax

class TemplightHandler(xml.sax.ContentHandler):
  def __init__(self):
    self.result = []

  def startElement(self, name, attrs):
    if name == 'Context':
      self.result.append(attrs['context'])

def main():
  if len(sys.argv) == 2:
    h = TemplightHandler()
    xml.sax.parse(sys.argv[1], h)
    for t in sorted(h.result):
      print t
  else:
    print 'Usage: %s <name of xml trace file>' % (sys.argv[0])

if __name__ == '__main__':
  main()

